telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

spring:
  application:
    name:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
db:
  driver:
    name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/db
  user: root
  password: root
  hikari:
    schema: telegram_bot_schema
    connection-init-sql: CREATE SCHEMA IF NOT EXISTS telegram_bot_schema
    connection-timeout: 10000


  flyway:
    baseline-on-migrate: true
    baseline-version: 0
